stages:
  - mirror
  - release

mirror:
  stage: mirror
  script:
    - echo "Release to Github"
  environment:
    name: github
    url: https://github.com/AdmitadSDK/android_sdk
  # always mirror master to github
  only:
    - master
  except:
    - tags


release:
  stage: release
  image: jangrewe/gitlab-ci-android
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x gradlew
  script:
    - echo "Release to Bintray"
    - set -e
    - echo "bintray.user=$BINTRAY_USER" > local.properties
    - echo "bintray.apikey=$BINTRAY_APIKEY" >> local.properties
    - echo "bintray.orgName=$BINTRAY_ORGNAME" >> local.properties
    - ./gradlew install
    - ./gradlew bintrayUpload
  environment:
    name: bintray
    url: https://bintray.com/admitadsdk/android_sdk/admitadstatisticsdk/$CI_COMMIT_TAG
  # release only protected tags
  only:
    - tags

